# Generated by Django 6.0.1 on 2026-02-02 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watchlist_user',
            field=models.ManyToManyField(null=True, related_name='watchlist_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
